### PR TITLE
Bye Phil

### PR DESCRIPTION
**Pull request by philbooth**

### CODE REVIEW

**Comment by lozette** [comment]
WHAT

**Comment by rowanmanning** [comment]
Yeah, docs are important Philbot

**Comment by lozette** [comment]
Officially strangest way to find out someone is leaving

**Comment by rowanmanning** [comment]
I like that it will say "a hour" at some point :)

**Comment by philbooth** [comment]
Apologies for the misleading comment, have fixed it.

Rowan, "a hour" was my going to be my parting easter egg for you guys! :)

**Pull request merged**
